version: "3.9"

services: 
  elasticsearch:
    container_name: toochi_chat_elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.7.1"
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - toochi_chat_elasticsearch_data:/usr/share/elasticsearch/data
      
  kibana:
    container_name: toochi_chat_kibana
    image: "docker.elastic.co/kibana/kibana:8.7.1"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
      
  postgres:
    container_name: toochi_chat_postgres
    image: postgres:latest
    ports:
      - "5555:5555"
    environment:
      POSTGRES_DB: "toochi_chat_database"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: toochi_chat_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes: 
  toochi_chat_elasticsearch_data:
  postgres_data:
  